import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const Azar = localFont({
  src: [
    {
      path: "../public/fonts/AzarMehr-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/AzarMehr-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="en" className={`${Azar.className} h-full antialiased scroll-smooth`}>
      <body className="flex flex-col min-h-full">
        <div className="flex flex-col gap-16 mx-auto max-w-6xl container">
          {children}
        </div>
      </body>
    </html>
  );
}
