import type { Metadata } from "next";
import localFont from "next/font/local"
import "./globals.css";

const Azar = localFont({
  src: [
    {
      path: '../public/fonts/AzarMehr-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/AzarMehr-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-azarmehr',
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${Azar.className}  h-full antialiased`}
    >
      <body className="flex flex-col min-h-full">{children}</body>
    </html>
  );
}
